development:
 adapter: postgresql
 encoding: unicode
 database: matchaflat_development
 pool: 5
 username: Cecilia
 password:

test:
 adapter: postgresql
 encoding: unicode
 database: matchaflat_test
 pool: 5
 username: Cecilia
 password:

production:
 adapter: postgresql
 encoding: unicode
 database: matchaflat_production
 pool: 5
 username: Cecilia
 password: